version: '3'

services:
  mariadb:
    container_name: mariadb
    build: "requirements/mariadb"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    ports:
     - "8083:3306"


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/justin/data/mysql
      o: bind
    
